# Generated by Django 5.2 on 2025-04-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_num',
        ),
    ]
