# Generated by Django 5.2 on 2025-05-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_rating_criteria_alter_service_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='execution_time',
            field=models.FloatField(default=1.0, verbose_name='Execution Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criteriaheaderfooter',
            name='footer_detected',
            field=models.BooleanField(verbose_name='Is footer detected'),
        ),
        migrations.AlterField(
            model_name='criteriaheaderfooter',
            name='footer_visible',
            field=models.BooleanField(verbose_name='Is footer visible'),
        ),
        migrations.AlterField(
            model_name='criteriaheaderfooter',
            name='header_detected',
            field=models.BooleanField(verbose_name='Is header detected'),
        ),
        migrations.AlterField(
            model_name='criteriaheaderfooter',
            name='header_visible',
            field=models.BooleanField(verbose_name='Is header visible'),
        ),
        migrations.AlterField(
            model_name='criteriaobjectdetection',
            name='detected_objects',
            field=models.IntegerField(verbose_name='Correctly detected objects'),
        ),
        migrations.AlterField(
            model_name='criteriaobjectdetection',
            name='visible_objects',
            field=models.IntegerField(verbose_name='Visible objects'),
        ),
        migrations.AlterField(
            model_name='criteriapagenumber',
            name='page_number_detected',
            field=models.BooleanField(verbose_name='Is page number detected'),
        ),
        migrations.AlterField(
            model_name='criteriapagenumber',
            name='page_number_visible',
            field=models.BooleanField(verbose_name='Is page number visible'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.service', verbose_name='Service'),
        ),
    ]
