# Generated by Django 5.2 on 2025-05-08 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_page_execution_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriaheaderfooter',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Additional notes'),
        ),
        migrations.AddField(
            model_name='criteriaobjectdetection',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Additional notes'),
        ),
        migrations.AddField(
            model_name='criteriapagenumber',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Additional notes'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='criteria',
            field=models.CharField(choices=[('PN', 'Page Number Criteria'), ('HF', 'Header Footer Criteria'), ('OD', 'Object Detection Criteria'), ('IMD', 'Image Detection Criteria'), ('OCR', 'OCR Criteria')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='criteria',
            field=models.CharField(choices=[('PN', 'Page Number Criteria'), ('HF', 'Header Footer Criteria'), ('OD', 'Object Detection Criteria'), ('IMD', 'Image Detection Criteria'), ('OCR', 'OCR Criteria')]),
        ),
        migrations.CreateModel(
            name='CriteriaImageDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Additional notes')),
                ('visible_images', models.IntegerField(verbose_name='Visible images')),
                ('detected_images', models.IntegerField(verbose_name='Correctly detected images')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app.rating')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CriteriaOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Additional notes')),
                ('word_recognition_errors', models.IntegerField(verbose_name='Number of misrecognized words')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app.rating')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
