# Generated by Django 5.2 on 2025-05-10 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_criteriaheaderfooter_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Execution Time')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('F', 'Full Page'), ('S', 'Page Section')], default='F'),
        ),
        migrations.AlterField(
            model_name='page',
            name='execution_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Execution Time'),
        ),
        migrations.CreateModel(
            name='PageSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.page')),
                ('pageset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pageset')),
            ],
        ),
    ]
