# Generated by Django 5.2 on 2025-05-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pageset_page_text_page_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriaobjectdetection',
            name='detected_objects',
        ),
        migrations.RemoveField(
            model_name='criteriaobjectdetection',
            name='visible_objects',
        ),
        migrations.AddField(
            model_name='criteriaobjectdetection',
            name='detected_image_objects',
            field=models.IntegerField(default=0, verbose_name='Correctly detected image objects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteriaobjectdetection',
            name='detected_table_objects',
            field=models.IntegerField(default=0, verbose_name='Correctly detected table objects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteriaobjectdetection',
            name='detected_text_objects',
            field=models.IntegerField(default=0, verbose_name='Correctly detected text objects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteriaobjectdetection',
            name='visible_image_objects',
            field=models.IntegerField(default=0, verbose_name='Visible image objects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteriaobjectdetection',
            name='visible_table_objects',
            field=models.IntegerField(default=0, verbose_name='Visible table objects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteriaobjectdetection',
            name='visible_text_objects',
            field=models.IntegerField(default=0, verbose_name='Visible text objects'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='criteria',
            field=models.CharField(choices=[('PN', 'Page Number Criteria'), ('HF', 'Header Footer Criteria'), ('OD', 'Object Detection Criteria'), ('IMD', 'Image Detection Criteria'), ('OCR', 'OCR Criteria'), ('OG', 'Object Groups Criteria')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='criteria',
            field=models.CharField(choices=[('PN', 'Page Number Criteria'), ('HF', 'Header Footer Criteria'), ('OD', 'Object Detection Criteria'), ('IMD', 'Image Detection Criteria'), ('OCR', 'OCR Criteria'), ('OG', 'Object Groups Criteria')]),
        ),
        migrations.CreateModel(
            name='CriteriaObjectGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Additional notes')),
                ('visible_groups', models.IntegerField(verbose_name='Visible object groups (image-description)')),
                ('detected_groups', models.IntegerField(verbose_name='Correctly detected object groups (image-description)')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app.rating')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
